[tool.poetry]
name = "poetry"
version = "1.2.0b1"
description = "Python dependency management and packaging made easy."
authors = [
    "Sébastien Eustace <sebastien@eustace.io>"
]
license = "MIT"

readme = "README.md"

homepage = "https://python-poetry.org/"
repository = "https://github.com/python-poetry/poetry"
documentation = "https://python-poetry.org/docs"

keywords = ["packaging", "dependency", "poetry"]

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

# Requirements
[tool.poetry.dependencies]
python = "^3.6"

poetry-core = "~1.0.7"
cleo = "^0.8.1"
clikit = "^0.6.2"
crashtest = { version = "^0.3.0", python = "^3.6" }
requests = "^2.18"
cachy = "^0.3.0"
requests-toolbelt = "^0.9.1"
cachecontrol = [
    { version = "^0.12.4", extras = ["filecache"], python = "<3.6" },
    { version = "^0.12.9", extras = ["filecache"], python = "^3.6" }
]
pkginfo = "^1.4"
html5lib = "^1.0"
shellingham = "^1.1"
tomlkit = ">=0.7.0,<1.0.0"
pexpect = "^4.7.0"
packaging = "^20.4"
virtualenv = { version = "^20.0.26" }

# The typing module is not in the stdlib in Python 2.7
typing = { version = "^3.6", python = "~2.7" }

# Use pathlib2 for Python 2.7
pathlib2 = { version = "^2.3", python = "~2.7" }
